name: unofficial_twitch_http
description: Package for making HTTP requests used by unofficial_twitch packages
version: 0.0.2
homepage: https://www.federicoviceconti.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: